[mcp_servers.chrome_devtools]
commad = "npx"
args = ["-y", "chrome-devtools-mcp@latest"]
startup_timeout_sec = 20
tool_timeout_sec = 45

[mcp_servers.next-devtools]
commad = "npx"
args = ["-y", "next-devtools-mcp@latest"]
